force-app/main/default/objects/ExternalLink__c/ExternalLink__c.object-meta.xml
<CustomObject>
    <label>ExternalLink</label>
    <nameField>
        <label>ExternalLink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExternalLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalLink__c/fields/WebsiteLink__c.field-meta.xml
<CustomField>
    <fullName>WebsiteLink__c</fullName>
    <label>WebsiteLink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ExternalLinksController.cls
public with sharing class ExternalLinksController {

    public List<ExternalLink__c> links {get;set;}
    public ExternalLink__c newLink {get;set;}

    ApexPages.StandardSetController ssc{
        get{
            ssc = new ApexPages.StandardSetController([SELECT Name, Description__c, WebsiteLink__c FROM ExternalLink__c]);
            ssc.setPageSize(50);
            return ssc;
        }
        set;
    }
    public ExternalLinksController() {
        this.newLink = new ExternalLink__c();
        this.links = [SELECT Name, Description__c, WebsiteLink__c FROM ExternalLink__c];
        
        //fetchRecords();
    }
    public void saveRecord(){
        
        try{
            Database.insert(newLink);
            fetchRecords();
            this.newLink = new ExternalLink__c();
        }
        catch(Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
            ApexPages.addMessage(msg);
        }      
    }
    

    public void fetchRecords(){
        this.links = ssc.getRecords();
    }

    public PageReference WorkOrderPage(){
        PageReference workPage = Page.WorkOrder;
        return workPage;
    }
    public PageReference OpportunityPage(){
        PageReference oppPage = Page.Opportunities;
        return oppPage;
    }
    public PageReference AccountsAndLeadsPage(){
        PageReference accAndLeadPage = Page.AccountsAndLeads;
        return accAndLeadPage;
    }
    public PageReference ContactsPage(){
        PageReference contactsPage = Page.Contacts;
        return contactsPage;
    }
    public PageReference OrderPage(){
        PageReference orderPage = Page.Order;
        return orderPage;
    }
    public PageReference LinksPage(){
        PageReference linksPage = Page.ExternalLinks;
        return linksPage;
    } 
    
}